#!/bin/bash

ARGS=("-x")
self=$(basename "$0")
if [[ "$self" = "pls" ]]; then
	ARGS=("-s");
fi

# Make sure /tmp/perflock exists and is world writable.  Don't rely on
# the redirection to create the file, or we'll have to run the
# subcommand with a bad umask.
(umask 000; touch /tmp/perflock)

(
    if ! flock -n "${ARGS[@]}" 200; then
        echo Waiting for lock >&2
        # wholock has to be setuid root, so it doesn't live on NFS.
        [ -x /usr/bin/wholock ] && /usr/bin/wholock >&2 200>&-
        flock "${ARGS[@]}" 200
        echo Got lock >&2
    fi

    # AC: This keeps claiming the system is busy when it isn't
#    if [ x$ARGS == x-x ]; then
#        [ -x `dirname $0`/loadet.pl ] && `dirname $0`/loadet.pl
#    fi

    # We need to close the lockfile FD in case the command forks off
    # children that it doesn't wait for (e.g., daemons)
    "$@" 200>&-
) 200>/tmp/perflock
