#!/bin/bash

ARGS=("-x")
self=$(basename "$0")
if [[ "$self" = "pls" ]]; then
	ARGS=("-s");
fi

if [[ ! -e /run/perflock ]]; then
	echo "/run/perflock did not exist"
	echo "make sure it exists and is writeable by any users of perflock"
	exit 1
fi

(
    if ! flock -n "${ARGS[@]}" 200; then
        echo Waiting for lock >&2
        # wholock has to be setuid root, so it doesn't live on NFS.
        [ -x /usr/bin/wholock ] && /usr/bin/wholock >&2 200>&-
        flock "${ARGS[@]}" 200
        echo Got lock >&2
    fi

    # AC: This keeps claiming the system is busy when it isn't
#    if [ x$ARGS == x-x ]; then
#        [ -x `dirname $0`/loadet.pl ] && `dirname $0`/loadet.pl
#    fi

    # We need to close the lockfile FD in case the command forks off
    # children that it doesn't wait for (e.g., daemons)
    "$@" 200>&-
) 200>/run/perflock
